### PR TITLE
Fix umbrella header errors for Carthage support

### PR DESCRIPTION
**Pull request by msanders**
Fixes 
screenshot 2016-10-18 15 50 22

when importing framework built by Carthage.

### CODE REVIEW

**Comment by reidmain** [comment]
Any update on this? We are trying to turn on warnings as errors for our application and unfortunately this is the last thing blocking us.

**Comment by ezarowny** [comment]
I'll give these changes a shot in a build and get back to you guys. I've never used Carthage before so this should be interesting.

**Comment by reidmain** [comment]
This isn't so much a Carthage thing as a module thing. If anyone tries including Rollbar as a module they will get this error. CocoaPods users are probably experiencing this as well if they generate frameworks but CocoaPods has the ability to say inhibit all warnings for a dependency.

**Comment by ezarowny** [comment]
What import style are you guys using? Quotes or angle brackets?

**Comment by reidmain** [comment]
We are using `import Rollbar` because we are using Swift.

**Comment by msanders** [comment]
`@import Rollbar;` or `#import <Rollbar/Rollbar.h>` from objc also generates the same warning. (assuming it's been built as a dynamic lib)

**Comment by ezarowny** [comment]
Xcode is so frustrating. If I import the master branch Framework and build I see your errors as warnings. But only the first time I build. Any idea how I can consistently make this happen?

**Comment by msanders** [comment]
Run `carthage build --no-skip-current` from the top level in the repo and drag the resulting framework to an example app. If necessary, may need to add [`copy-frameworks` script](https://github.com/Carthage/Carthage#if-youre-building-for-ios-tvos-or-watchos) as a build phase as well.

Alternatively, setup an example app with `RollbarFramework` library as a target dependency and import as a module from there.

**Comment by reidmain** [comment]
@ezarowny I've noticed that too. I just clean the project and then build again and that causes the warnings to re-appear.

**Comment by ezarowny** [comment]
Hey guys, I'll try to finish up testing today and get a release out.

**Comment by reidmain** [comment]
Sounds great. Thank you very much. If you want someone to sanity check before you cut the release just ping when its on a branch and I can do a quick build locally.

**Comment by ezarowny** [comment]
What target are you building in Xcode? The umbrella header warnings aren't in the Carthage output or Xcode. For reference, I'm on Xcode 8.1.

**Comment by ezarowny** [comment]
Ah finally, reproducibility! Let me tinker with this a bit to make sure things behave as expected. I should be able to cut a release pretty soon if all goes well.

**Comment by ezarowny** [comment]
@reidmain can you test the master branch for me?

**Comment by reidmain** [comment]
@ezarowny sure I'm building it now.

**Comment by ezarowny** [comment]
Thanks. I made a small change to bitcode support while I was in there but I doubt that would affect this.

**Comment by reidmain** [comment]
I am getting compilation errors for some reason. The Swift compiler is saying that it can't find the module `CrashReporter` or `Rollbar` now. I'll dig into why.

**Comment by ezarowny** [comment]
Ah yeah, me too. I had the wrong framework import. @msanders any idea?

**Comment by reidmain** [comment]
It looks like in my Swift code `import Rollbar` is causing `Could not build Objective-C module 'Rollbar'`

**Comment by reidmain** [comment]
This looks to have something to do with the `@import CrashReporter;` line inside the `RollbarFramework.h` file. If I comment out that line then the app builds. I don't know too much about moduemaps myself. Do they need to contain any information about what libraries they are dependent on? Because before the `@import CrashReporter;` technically wasn't in the umbrella header of the module and now it is.

**Comment by ezarowny** [comment]
PLCrashReport probably isn't being built as a module in the first place. I'll see what I can dig up.

**Comment by ezarowny** [comment]
I'm not sure this is actually necessary. Why couldn't we use a bridging header here?

**Comment by reidmain** [comment]
Unfortunately I'm not sure what you mean by "use a bridging header".

**Comment by ezarowny** [comment]
Something like https://randexdev.com/2014/08/swift-frameworks/ although I'm not sure if this applies in our case.

**Comment by reidmain** [comment]
My understanding is the bridging header is used at an app level to expose things to Swift, if needed.

We have a number of frameworks included in our app project that aren't mentioned in the bridging header and are only referenced using `import framework`. If a framework doesn't specify a modulemap I was under the impression that the the name of the framework is implicitly the module and then `{name}.h` is the umbrella header. So for the majority of frameworks they didn't need to do anything to work specifically with Swift because they were following this by convention.

Now as to how to use a vendored framework in a module I have absolutely no idea. It was my understanding that you either had to manually pack the vendored framework into the module (which it does not look like is being done here) or you make it the responsibility of the developer to also link the dependency of the module to their app. This is essentially what CocoaPods does. Any dependencies are just counted as another target that your app links against.

So the tl;dr is I don't think bridging headers matter in this case and I am not exactly sure how CrashReporter.framework is ever included in the apps that use Rollbar.

**Comment by reidmain** [comment]
It is not clear to me why `@import CrashReporter;` is needed in `RollbarFramework.h`. The point of that header file is essentially to expose everything that is public in the framework. CrashReporter has no need to be exposed publicly. It is an implementation detail of Rollbar. In theory if you wanted to swap it in the future it shouldn't matter correct?

The only place CrashReporter seems to be imported is inside the implementation of Rollbar https://github.com/rollbar/rollbar-ios/blob/1b02dd464aad8fef5237d44d3e574cdf9214f684/Rollbar/Rollbar.m#L12

**Comment by ezarowny** [comment]
You might be onto something there. Let me try using it without CrashReporter being exposed.

**Comment by ezarowny** [comment]
Eh, I've only managed to crash my app at this point. How are you using/linking against the `Rollbar.framework` file?

**Comment by reidmain** [comment]
Since it is integrated using Carthage it is included under the "Link Binary With Libraries" section of "Build Phases" and then mentioned again in a custom section called "Copy Carthage Frameworks".

If you search https://github.com/Carthage/Carthage for `/usr/local/bin/carthage copy-frameworks
` you can see the documentation for why this custom section is necessary.

**Comment by ezarowny** [comment]
I haven't been able to make much progress with this yet. Any luck on your side?

**Comment by reidmain** [comment]
Apologies I haven't. Trying to get rid of these warnings have taken a bit of a back seat to other issues. @msanders were you able to integrate master using Carthage?

**Comment by ezarowny** [comment]
I think what I'm going to end up doing here is attempting to compile PLCrashReporter with rollbar-ios instead of making it a second required framework.

**Comment by reidmain** [comment]
So I used Carthage to checkout master and build it into our app. As expected it complained about not being able to find CrashReporter. I then went into the Carthage/Checkout folder, opened up the Rollbar Xcode project and removed `@import CrashReporter;` from the `RollbarFramework.h`. I then rebuilt the framework using Carthage, cleaned my app project, built and ran it and it seemed to work.

Now I realize this information may not be super useful to you because we don't use CrashReporter with Rollbar. We disable it (`Rollbar.initWithAccessToken(rollToken, configuration: config, enableCrashReporter: false`) so that could possibly explain why removing it from the umbrella header does nothing.

But I figured this was a nice tidbit of information to see how the app wasn't crashing for me if I removed that `@import`.

**Comment by ezarowny** [comment]
@reidmain out of sheer curiosity, what do you do when your app crashes?

**Comment by msanders** [comment]
We also disabled the crash reporter for Rollbar. In our fork, we actually had to remove it because it was interfering with our other crash reporter, Fabric (even when turned off). Would be nice if there were a variant of the SDK with `PLCrashReporter` removed, which would avoid this issue.

**Comment by ezarowny** [comment]
Yeah, I believe iOS generally can't handle more than one crash reporter. We mention it somewhere in the README. Thanks for the information.

**Comment by reidmain** [comment]
@ezarowny we are using Crashlytics to gather crashes as well as a lot of the typical vanity analytics.

**Pull request merged**
