### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ezarowny**
Update Bitcode instructions

### CODE REVIEW

**Comment by ezarowny** [comment]
@rivkahstandig3636 does this make sense?

**Comment by rivkahstandig3636** [comment]
@ezarowny Makes total sense, but I would recommend adding some screenshots of what to do in your step by step instructions. Thank you!

**Comment by brianr** [comment]
Going to merge this as-is so we can get this improvement into the wild :) Screenshots would be awesome though.

**Comment by ezarowny** [comment]
It'd be hard to get screenshots of everything though. We'd need something released onto iTunes Connect.

**Pull request merged**
