### PR TITLE
Issue 38 Resolve atomic / nonatomic warnings

### LINKED ISSUE #38: Warning: 'atomic' attribute does not match the inherited property
Hi!
I've integrated version 0.2.0 via CocoaPods (XCode 8.2.1) and there are several warnings:
standalone xcworkspace 2017-02-02 15-43-46

```personId```, ```personUsername```, ```personEmail``` have different attributes in ```RollbarConfiguration.h``` and ```RollbarConfiguration.m files```.

What is the reason of such difference?

### PR DESCRIPTION
**Pull request by pouriaalmassi**
- Resolves warnings generated by property attributes declared `atomic` which are then inherited by properties which declared as `nonatomic`.
- Minor formatting change.

Resolves #38

### CODE REVIEW

**Comment by rokob** [comment]
That atomically has nothing to do with the atomicness of the properties. I think the fix would be to not tell the compiler we want setters via the class extension trick and rather just set the ivars directly in `setPersonId:username:email:`

**Comment by rokob** [comment]
But that would require also changing the properties in the header to nonatomic because that direct ivar access would otherwise violate that contract.

**Comment by pouriaalmassi** [comment]
The three properties declared in the header we marked with `readonly` so I take it we don't want anyone modifying these properties outside of `setPersonId:username:email:`. What if we did something like this?

```
diff --git a/Rollbar/RollbarConfiguration.h b/Rollbar/RollbarConfiguration.h
index ee7d14e..7a505bc 100644
--- a/Rollbar/RollbarConfiguration.h
+++ b/Rollbar/RollbarConfiguration.h
@@ -25,12 +25,13 @@
 
 - (NSDictionary *)customData;
 
+- (NSString *)personId;
+- (NSString *)personUsername;
+- (NSString *)personEmail;
+
 @property (nonatomic, copy) NSString *accessToken;
 @property (nonatomic, copy) NSString *environment;
 @property (nonatomic, copy) NSString *endpoint;
 @property (nonatomic, copy) NSString *crashLevel;
-@property (readonly, nonatomic, copy) NSString *personId;
-@property (readonly, nonatomic, copy) NSString *personUsername;
-@property (readonly, nonatomic, copy) NSString *personEmail;
 
 @end
diff --git a/Rollbar/RollbarConfiguration.m b/Rollbar/RollbarConfiguration.m
index 2508600..c67791f 100644
--- a/Rollbar/RollbarConfiguration.m
+++ b/Rollbar/RollbarConfiguration.m
@@ -152,4 +152,18 @@ - (NSArray*)getProperties {
 - (NSDictionary *)customData {
     return [NSDictionary dictionaryWithDictionary:customData];
 }
+
+- (NSString *)personId {
+    return self.personId;
+}
+
+- (NSString *)personUsername {
+    return self.personUsername;
+}
+
+- (NSString *)personEmail {
+    return self.personEmail;
+}
+
+
 @end

```

**Comment by rokob** [comment]
```
- (NSString *)personId {
    return self.personId;
}
```
is an infinite loop. The question is whether we need atomic properties. The issue with the way things are currently written is that using the single setter for the three readonly properties and calling their individual setters is not thread safe. Even though we use atomic properties, the fact is that there could be calls interleaved between each setter call, so as is the class is trying to be thread safe but has bugs. If we want it to be thread safe and have read only properties, but also have a setter for all of the read only properties at once, then we need to use a synchronization primitive (mutex, @synchronized, etc) correctly in both custom getters and the custom setter. We would need to make the custom getters read directly from the ivars, but protect the read with our locking mechanism.

**Comment by pouriaalmassi** [comment]
@rokob Please see the latest commit. I'm unsure of how to ensure the correctness of this as there don't appear to be any tests in place.

**Pull request closed without merging**
