### PR TITLE
Release candidate: v2.0.0-alpha13

### PR DESCRIPTION
**Pull request by akornich**
## Description of the change

- all the changes to files in the Demo folder are about sample code cleanup and fixes related to our SDK API changes as well as project files updates suggested by the latest Xcode 12 upgrade
- changes to *.podspec and Package.swift files are about version bump and dropping support of iOS v8
- RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarConfig.m has changes to built-in notifier version and the conditional compilation preprocessor directives (#elseif into #elif)
- changes to Rollbar.h/m and RollbarLogger.h/m are about cleaning up APIs and making them more Swift friendly. Also moving logging level from string value to the RollbarLevel enum type.
- the rest is unit test adjustments related to the API changes above.

## Type of change
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues

> Fix [#212]() 
### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Comment by mrunalk** [comment]
Can you describe major changes in the PR description so that it is easy to review?

**Comment by akornich** [comment]
- all the changes to files in the Demo folder are about sample code cleanup and fixes related to our SDK API changes as well as project files updates suggested by the latest Xcode 12 upgrade
- changes to *.podspec and Package.swift files are about version bump and dropping support of iOS v8
- RollbarNotifier/Sources/RollbarNotifier/DTOs/RollbarConfig.m has changes to built-in notifier version and the conditional compilation preprocessor directives (#elseif into #elif)
- changes to Rollbar.h/m and RollbarLogger.h/m are about cleaning up APIs and making them more Swift friendly. Also moving logging level from string value to the RollbarLevel enum type.
- the rest is unit test adjustments related to the API changes above.

**Review by ajtran — APPROVED** [review]
There's some commented out code in the tests. Do you mean to leave that there? Besides that, it looks good to me!

**Comment by akornich** [comment]
> There's some commented out code in the tests. Do you mean to leave that there? Besides that, it looks good to me!

yes, i'll be doing another clean-up path before we go from beta to GA release...

**Pull request merged**
