### PR TITLE
Added framework target for Carthage compatibility

### PR DESCRIPTION
**Pull request by mpurland**

### CODE REVIEW

**Comment by dlsteuer** [comment]
Thanks for the pull request, works great!

**Comment by brianr** [comment]
What do we need to do to maintain this going for new releases going forward?

**Comment by dlsteuer** [comment]
I don't think we need to change anything else going forward, Carthage only works with dynamic frameworks, which rollbar-ios wasn't built as in the first place.

**Comment by mpurland** [comment]
If the framework target is maintained then it should remain Carthage compatible.

**Pull request merged**
