### PR TITLE
Lower deployment target to iOS 9.0

### LINKED ISSUE #338: Deployment target for Rollbar changed to iOS 12.0
After update I'm getting this warning while archiving my project

```
ld: warning: dylib (../Rollbar.framework/Rollbar) was built for newer iOS version (12.0) than being linked (11.0)
```

I think this commit https://github.com/rollbar/rollbar-ios/commit/2949df4645aea778096394095c0a81381f013935 somehow changed it. I'm really sure you wanted to drop only iOS 8 support

### PR DESCRIPTION
**Pull request by GRiMe2D**
## Description of the change
Removed all target overrides for iOS and macOS deployment target and set project wide. Lowered iOS deployment target from iOS 12.0 to iOS 9.0

Screen Shot 2020-11-27 at 1 30 19 PM
Screen Shot 2020-11-27 at 1 30 43 PM

## Type of change
- [X] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Related issues
Fix #338 

### Development

- [ ] Lint rules pass locally
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development

### Code review 

- [ ]  This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached
- [ ] "Ready for review" label attached to the PR and reviewers mentioned in a comment
- [ ] Changes have been reviewed by at least one other engineer
- [ ] Issue from task tracker has a link to this pull request

### CODE REVIEW

**Review by akornich — COMMENTED** [review]
@GRiMe2D , thanks for the PR! One question - did you try building the SDK with these changes under Xcode 12?

**Comment by GRiMe2D** [comment]
@akornich yes, it compiles normally, but Xcode recommends to switch to iOS 12.

Xcode 12 only dropped iOS 8 support, but iOS 9 and later are accessible. I'm currently using my fork in a project and all seems running ok.

**Comment by akornich** [comment]
@GRiMe2D , got it. The build issue under Xcode 12  was actually triggered within KSCrash codebase that we depend on and it seemed persistent until I bumped the min iOS target to v12. I know KSCrash guys are already looking into it on their side to have an actual fix. But since you confirmed your changes behave with Xcode 12 let's go with it. Thank you!

**Review by akornich — APPROVED** [review]
lgtm

**Pull request merged**
